### PR TITLE
allow specifying the seed packages

### PR DESCRIPTION
**Pull request by gaborbernat**
i have a dream

### CODE REVIEW

**Comment by gaborbernat** [comment]
Withdrawn.

**Comment by sinoroc** [comment]
Am I understanding this correctly that the original intention of that change was to allow users to specify wheels (in addition to _pip_, _setuptools_, and _wheel_) that would be seeded into the virtual environment?

**Comment by gaborbernat** [comment]
Yes. However, in the end, we decided against this, and now only allow specifying the exact version constraint for pip/setuptools/wheel. Note one could write a plugin for virtualenv that triggers extra seed packages post environment creation, that now can be installed via pip.

**Comment by sinoroc** [comment]
That answers the question. Thanks!

**Pull request closed without merging**
