### PR TITLE
[WIP] The next-gen virtualenv (rewrite)

### LINKED ISSUE #1366: [RFC] The next generation of virtualenv
Following the discussion in [1362](https://github.com/pypa/virtualenv/issues/1362) it became apparent that for virtualenv to be able to support the new world (Windows Store installs, venv interpreters) we need some major change of direction.

Here's my proposal for going ahead with this project. This will be a major refactor for the project, that plans to keep existing interface compatibility though.

# Project goal
- create **a fresh copy of the system (invoker) python that has its own custom, separately controllable package list**,
- an interface and behaviour that's as much as possible consistent across all supported Python environments (e.g. backport new venv features to older interpreters),
- extensible (both creation and shell activation script support wise),
- PyPi package (ability to upgrade out of band with interpreter).

# Planned features
- **universal pypi wheel**,
- **cross-platform** - Windows, all UNIX flavours, MacOS.
- **support for most supported pythons**, the initial pool of supported Python version: ``python2.7``, ``python3.4``, ``python3.5``, ``python3.5``, ``pypy3``, ``pypy2`` (hoping for IronPython and Jython at some point - any other ones we should support?)
- A **two year grace period** of support: our interface will keep the interpreter support for two more years past its EOL: creating virtual environments is so basic that this package is the last one that should drop compatibility. During this transitional two years period, we guarantee bug fixes and compatibility. New feature support is a best effort though.
- ability to **specify the target python** (we'll use PEP-514/PEP-394/explicit link to discover these versions) and create virtual environments even if that target does not have this package installed
- **prefer built-in venv**: if the target python has venv we'll create the environment using that (and then perform subsequent operations on that to facilitate other guarantees we offer)
- ability to provision **seed packages** (after the creation of the virtual environments this packages will be already installed):
  
  - we accept PEP-508 format,
  - ability to reach out to PyPi to get latest matching the spec, or offline only (such install packages must be offline)
  - by default ``pip``, ``setuptools`` and ``wheel`` are the seed packages (these packages are also automatically injected as offline wheel packages)
- **interfaces**:
   
  - CLI interface (``python -m virtualenv``, ``virtualenv``)
  - wheel interface (env ``PYTHONPATH=/t/path/to/virtualenv.whl python -m virtualenv``) - universal wheel,
  - zipapp interface,
  - API interface: ``import virtualenv; virtualenv.create("target")``
- **shell support** -  activation/deactivation scripts and prompt environment variables - by default we generate:

  - bash / zsh,
  - csh,
  - fish,
  - powershell, 
  - xonsh,
  - cmd,
  - python,
  - a well-defined API to install custom shell scripts (maybe as part of the plugin system).

- **three-layered configuration system**, each option is determined as follows: 

  - first, ini configuration support (a global ini config present in the users home),
  - second, environment variables having the ``VIRTUALENV_`` prefix,
  - finally, command line options (argparse powered)

- **plugin system** these are extension points the user can inject their own custom logic, and generate an extended version of virtualenv (current bootstrapping logic):
  
   - extend parser (add your own custom CLI flags),
   - adjust options (change options after CLI parse),
   - after install (perform some operation once the virtual environment creation is done)
- **virtualenv support** - the operation should work even if the invoking python is a virtualenv created python,
- **venv support** - the operation should work even if the invoking python is a virtualenv created python,
- **relocatable environments**: an environment should keep working as long as the root python is not removed from the OS (e.g. renaming the root environment folder should not break things).

# Difference from stdlib venv
How we differ from the standard library venv? The virtualenv package plans to be:
- a PyPi package, as such will be more often upgraded, easier to keep up to date and offer feature parity across pythons,
- built-in interpreter discovery and cross interpreter support,
- more interfaces (zippapp, wheel, installed package),
- easier customization - plugin system,
- be the testing ground for new features (which down the line may make it into venv),
- longer EOL.

In general, offer features that other downstream tools (for example tox, pre-commit, pipenv, pipsi, pipx) who need virtual environments as an API would want.

PyPy members (and the public please too) share your thoughts or plus one if you agree. @pfmoore @dstufft @di @pradyunsg @cjerdonek @ncoghlan @jaraco @techalchemy @uranusjr @pganssle @benoit-pierre @dholth @lkollar @takluyver @zooba

### PR DESCRIPTION
**Pull request by gaborbernat**
Resolves #1366 #697.

### CODE REVIEW

**Comment by pradyunsg** [comment]
@gaborbernat I took the liberty of renaming this PR -- lemme know if that's not OK with you. ;)

Also, please feel free to ping me whenever you're OK with getting feedback/inputs on this.

**Comment by gaborbernat** [comment]
@pradyunsg still WIP - I would say probably in 2-3 weeks will be ready for review 🤔 need to first add tests for target discovery to reach 100% coverage, do the package boostrapping and activation parts (envs created at this stage are pip-less). Windows 3.7 and 3.8 support is to be done also; but that can wait for after first release.

**Comment by pradyunsg** [comment]
Opinion: We should reset by opening a new PR for this and closing this one, once we're at a point for reviews, since the force-push messages are annoying IMO. 🤷🏻‍♂️

**Comment by ssbarnea** [comment]
@gaborbernat You are really brave. Many went this path and nobody returned! ;)

Still, if succeeding on this would be a huge achievement.

**Comment by gaborbernat** [comment]
Initial encouraging signs, old way:

```bash
rm perf -rf; time virtualenv --no-download perf --no-wheel
New python executable in /virtualenv/perf/bin/python
Installing setuptools, pip...
done.
        2.72 real         1.80 user         0.86 sys
```

New way:

```bash
rm perf -rf; time .tox/dev/bin/virtualenv --no-download perf                                                                                                                                                                                                                                        
create with venv /.pyenv/versions/3.7.4/bin/python3.7 -m venv --without-pip /virtualenv/perf
[2019-10-15 19:04:56,429] INFO [/virtualenv/src/virtualenv/interpreters/create/api.py:71]
        0.28 real         0.20 user         0.05 sys
```

**Comment by pfmoore** [comment]
Out of curiosity, is the closure of this PR a good thing or a bad thing? I.e., is the work ready for inclusion in master, or has it been abandoned?

**Comment by gaborbernat** [comment]
I've got someone helping me out on development, so moved the work over to the feature branch so they can create prs against that. So a great news 👍but we're not there yet release wise, I've been very flooded with other stuff in the last month so did not make much progress, but still continue grinding on it 👍

**Pull request closed without merging**
