### PR TITLE
Fix typo in setup.cfg

### LINKED ISSUE #1857: AttributeError: module 'virtualenv.activation.python' has no attribute 'PestythonActivator'
I think it's just a typo in the latest release...

### PR DESCRIPTION
**Pull request by RowdyHowell**
Closes #1857 

- [X] ran the linter to address style issues (``tox -e fix_lint``)
- [X] wrote descriptive pull request text
- [X] ensured there are test(s) validating the fix
- [X] added news fragment in ``docs/changelog`` folder
- [X] updated/extended the documentation

### CODE REVIEW

**Comment by pascal-de-ladurantaye** [comment]
@gaborbernat please LGTM

**Comment by andrewboss** [comment]
LGTM!

**Comment by gaborbernat** [comment]
Give me 5 mintues.

**Comment by gaborbernat** [comment]
Sorry for that guys, my mistake, fix out under https://pypi.org/project/virtualenv/20.0.23/

**Comment by fj-sanchez** [comment]
Doesn't look that good to me... the fact that a test hasn't been introduced won't stop this from happening again.

**Comment by GPHemsley** [comment]
@fj-sanchez The entire testsuite failed because of this bug, and it was still released; adding another test isn't gonna make much difference...

**Comment by fj-sanchez** [comment]
Ok, I didn't realise that was the case. Why isn't enforced a pass on all the tests?

**Comment by rowanseymour** [comment]
I think this makes a nice case study in why it's good practice to do automated releases from CI.. after tests pass

**Comment by gaborbernat** [comment]
Just to sum up the discussion:
- This repository has the release process automated and happens automatically on the tag after tests pass.
- However, a CI run takes fairly long: 25-30 minutes.
- There was a PR that upgraded the embedded versions that passed. It lacked the changelog entries for. So decided to add them, and append it. While doing this change by mistake the ``setup.cfg`` got modified. This project is maintained completely in the free and voluntary time of maintainers (which at the moment involves just me). Someone requested a release to fix issues generated by the release of importlib.metadata v2. At this point was 7pm local time on a Friday, and considering my available time was running to an end I decided to expedite the release by force-merging the PR and the release. In hindsight, this was obviously a bad idea; but the reason for it was my intent to accommodate a release quicker.

I'm deeply sorry that this affected everyone's Friday, lessons learned and hope this will not happen again going ahead. Just for context, this was my 42nd release of this project throughout the last 2 years. I think this was the first truly broken release and hope to stay as such for at least another 100.

**Pull request merged**
