### PR TITLE
Fix Tcl for Python 3.3-

### PR DESCRIPTION
**Pull request by techtonik**
https://github.com/pypa/virtualenv/pull/888#issuecomment-222345374

### CODE REVIEW

**Comment by yan12125** [comment]
It's working :) https://ci.appveyor.com/project/yan12125/virtualenv/build/1.0.6

**Comment by asottile** [comment]
Breaking my build here as well: https://ci.appveyor.com/project/asottile/pre-commit/build/1.0.604/job/tcxhyj6l932c8anm

Looking forward to this fix :)

**Comment by techtonik** [comment]
@dstufft can you take a look at this?

**Comment by Ivoz** [comment]
I think something like #933 will be a better option than this

**Pull request closed without merging**
