### PR TITLE
cases sensitivity on windows - Issue #12

### PR DESCRIPTION
**Pull request by zvodd**
Possibly also related to #935 and #72.

### CODE REVIEW

**Comment by zvodd** [comment]
I did a deep dive on this bug because it was interrupting my work flow at the time ( a **while** ago). Honestly, I feel a little out of my depth here as I haven't used or read this code base in over a year.
In bad practice I didn't record anything about the manual testing I did ( on 2 Windows PCs 1 Linux server) and never even looked at the packages unit tests. Oops...

BTW I pressed the **Update branch** button - I don't know what it does. /facepalm

Still, I'd be happy to take another look at it. Sometime soon... holiday season is imminent and a don't get much time to sit down and work during that period.

**Comment by gaborbernat** [comment]
No worries, whenever you get some availability for it 👍

**Comment by gaborbernat** [comment]
@zvodd are you still open to fix this? thanks!

**Comment by zvodd** [comment]
Yes I'm looking into it.
I also noticed there was a [commit ](https://github.com/pypa/virtualenv/commit/733586aa2a58ea9fd268b45911a75d0df2d7452d)that addressed Issue #837 which I think my patch might regresses.
I am sitting a new patch that should address #12, #837, and #72 
I think to address #935, it requires walking the full file path for each file and prefix.

I'm not exactly sure what testing to do. Partly because I haven't been able to track down the environmental factor causing (at least one of) the bug conditions.

I guess validate `change_prefix` for consistently cased output (on windows?) with a variety of different file paths? This should be written as a tox test?

**Comment by gaborbernat** [comment]
I think pytest test is fine, with skip if not windows.

**Comment by and-semakin** [comment]
Hey, it would be nice to merge this PR :)

**Comment by gaborbernat** [comment]
We need someone to fix merge conflicts and add test to validate the change. Once that's done we can merge it 👍

**Comment by gaborbernat** [comment]
closing this, maybe during the rewrite we can fix it separately.

**Pull request closed without merging**
