### PR TITLE
Only remove the virtualenv from the PATH

### PR DESCRIPTION
**Pull request by robsonpeixoto**
Today we have to use a lot of tools to develop a system, and because of it we need version managers from python, node, ruby ...
The current activate implementation will keep a old path saved and change using the new one.
But after the deactivate, it will restore the old path and the developer can loose all configuration from other version manager.

With this PR it will only remove the PATH the VIRTUAL_ENV path.

### CODE REVIEW

**Comment by techtonik** [comment]
I guess the decision was that `activate/deactivate` should be atomic. For example, if tests that are run in `virtualenv` modify PATH, you can get plenty of pain after you exit.

**Comment by robsonpeixoto** [comment]
Are you caring about the code change the PATH? Is the virtualenv responsibility take care about the user code?

**Comment by techtonik** [comment]
`virtualenv` responsibility is to provide an isolated environment for running Python programs. Why should it care about user code?

**Comment by robsonpeixoto** [comment]
Sorry, I do not understand it: `For example, if tests that are run in virtualenv modify PATH, you can get plenty of pain after you exit.`

But I get your point. Are there a way to change the `activate.fish` template?

**Comment by techtonik** [comment]
The point is that scripts inside `virtualenv` can modify environment variables too, and it is better to clean this before exit. But you may try to get more opinions by asking in mailing list.

> Are there a way to change the activate.fish template?

You've already changed it. Did you forget to run `bin/rebuild-script.py`?

**Pull request closed without merging**
