### PR TITLE
Fix path_locations for PyPy on Windows

### PR DESCRIPTION
**Pull request by blueyed**
Ref: https://github.com/pypa/virtualenv/commit/81904e4#r34565082
Ref: https://github.com/tox-dev/tox/issues/1389

### CODE REVIEW

**Comment by blueyed** [comment]
@gaborbernat 
Please feel free to pick this up from here.

**Comment by gaborbernat** [comment]
Thanks!

**Comment by blueyed** [comment]
> We should add tests for this stuff.

:+1: 
I've hoped for one being added in the process - assuming it would be easier for you with knowledge around the code/tests.

**Comment by blueyed** [comment]
@gaborbernat 
Can we have a release for this please?
Projects are already working around this: https://github.com/pytest-dev/pytest-cov/pull/321/files#diff-2c3fc6b6d1681a77c3ee4a70b3763530

**Comment by gaborbernat** [comment]
@blueyed rolling under https://dev.azure.com/pypa/virtualenv/_build/results?buildId=11337

**Pull request merged**
