### PR TITLE
Fixes #750.

### LINKED ISSUE #750: UnboundLocalError using -p option on Windows
When I use the `-p` option, I get `UnboundLocalError: local variable 'original_python' referenced before assignment`

```
C:\Users\niklas\Desktop\stack>virtualenv env -p "C:\maxon\Cinema 4D R15 Dev\resource\modules\python\res\Python.win64.framework\python.exe" --no-site-packages
Running virtualenv with interpreter C:\maxon\Cinema 4D R15 Dev\resource\modules\python\res\Python.win64.framework\python.exe
Overwriting env\lib\site.py with new content
New python executable in env\Scripts\python.exe
Traceback (most recent call last):
  File "F:\Python27\lib\site-packages\virtualenv.py", line 2352, in <module>
    main()
  File "F:\Python27\lib\site-packages\virtualenv.py", line 825, in main
    symlink=options.symlink)
  File "F:\Python27\lib\site-packages\virtualenv.py", line 985, in create_environment
    site_packages=site_packages, clear=clear, symlink=symlink))
  File "F:\Python27\lib\site-packages\virtualenv.py", line 1363, in install_python
    shutil.copy(original_python, py_executable)
UnboundLocalError: local variable 'original_python' referenced before assignment
```

The referenced Python version is 2.6.4, using virtualenv 12.1.1

### PR DESCRIPTION
**Pull request by NiklasRosenstein**

### CODE REVIEW

**Comment by BrownTruck** [comment]
Hello!

As part of an effort to ease the contribution process and adopt a more standard workflow virtualenv has switched to doing development on the ``master`` branch. However, this Pull Request was made against the ``develop`` branch so it will need to be resubmitted against ``master``.

If you do nothing, this Pull Request will be automatically migrated by @BrownTruck for you.

If you would like to retain control over this pull request then you should resubmit it against the ``master`` branch, closing and referencing the original Pull Request.

If you choose to migrate this Pull Request yourself, here is an example message that you can copy and paste:

```


---

*This was migrated from pypa/virtualenv#829 to reparent it to the ``master`` branch. Please see original pull request for any previous discussion.*
```

If this pull request is no longer needed, please feel free to close it.

**Comment by NiklasRosenstein** [comment]
Hi @BrownTruck, I'm unsure how I can re-submit the pull request since I deleted my fork already.

**Comment by NiklasRosenstein** [comment]
Closed because of #697?

**Comment by selurvedu** [comment]
> Hi @BrownTruck, I'm unsure how I can re-submit the pull request since I deleted my fork already.

You can get your branch back. Make a new fork, then execute this:

```shell
$ git clone git://github.com/pypa/virtualenv.git
Cloning into 'virtualenv'...
remote: Counting objects: 5933, done.
remote: Total 5933 (delta 0), reused 0 (delta 0), pack-reused 5933
Receiving objects: 100% (5933/5933), 52.03 MiB | 1.17 MiB/s, done.
Resolving deltas: 100% (3806/3806), done.
Checking connectivity... done.
$ cd virtualenv/
$ git ls-remote | grep pull/829
From git://github.com/pypa/virtualenv.git
b3c5b58cf7c95bb093a6d70070e2ad2d7fed8237        refs/pull/829/head
29e14aefe488f79a441aa8e5047d08ef7809057a        refs/pull/829/merge
$ git fetch origin refs/pull/829/head
remote: Counting objects: 3, done.
remote: Total 3 (delta 1), reused 1 (delta 1), pack-reused 1
Unpacking objects: 100% (3/3), done.
From git://github.com/pypa/virtualenv
 * branch            refs/pull/829/head -> FETCH_HEAD
$ git checkout -b fix-750 FETCH_HEAD
Switched to a new branch 'fix-750'
$ git remote add myfork git+ssh://github.com/NiklasRosenstein/virtualenv.git
$ git push -u myfork
```

**Pull request closed without merging**
