### PR TITLE
Lint activate.ps1

### PR DESCRIPTION
**Pull request by jayvdb**
Fix PSScriptAnalyzer warnings, and follow style from
-Setting CodeFormattingOTBS

Closes https://github.com/pypa/virtualenv/issues/1371

### CODE REVIEW

**Comment by jayvdb** [comment]
Now passes the following two commands
```ps1
Invoke-ScriptAnalyzer activate.ps1
Invoke-ScriptAnalyzer -Setting CodeFormattingOTBS activate.ps1
```

**Comment by jayvdb** [comment]
Note that while the tests pass, I dont have Windows so I havent played with this. I do have pwsh for Linux, and I could test with that if it is known to work (and add tests for that?)

It should be reviewed by someone who can verify that it works correctly, or identify extra tests that need to be written to verify it is working correctly.

**Comment by gaborbernat** [comment]
please run tox -e embed and commit the generated change

**Comment by jayvdb** [comment]
I got a non-zero exit code, but I guess that is OK.

```console
> python3 -m tox -e embed
embed create: /home/jayvdb/projects/python/virtualenv/.tox/embed
embed installdeps: pip >= 19.1.1
embed run-test-pre: PYTHONHASHSEED='4009722547'
embed run-test: commands[0] | python update_embedded.py
Found file site.py
  File up to date (crc: 458366c2)
Found file activate.sh
  File up to date (crc: 0d63b5ff)
Found file activate.fish
  File up to date (crc: e5f7c440)
Found file activate.csh
  File up to date (crc: ff2bf2f5)
Found file activate.xsh
  File up to date (crc: fec22784)
Found file activate.bat
  File up to date (crc: 0f734cb0)
Found file deactivate.bat
  File up to date (crc: 9ddc164f)
Found file activate.ps1
  Content changed (crc: d8005bb6 -> c7bc785c)
Found file distutils-init.py
  File up to date (crc: affaad52)
Found file distutils.cfg
  File up to date (crc: cd607b02)
Found file activate_this.py
  File up to date (crc: 544ed6ab)
Found file python-config
  File up to date (crc: 9a7177a5)
Content updated; overwriting... done.
ERROR: InvocationError for command /home/jayvdb/projects/python/virtualenv/.tox/embed/bin/python update_embedded.py (exited with code 1)
________________________________________________________________________________ summary _________________________________________________________________________________
ERROR:   embed: commands failed
```

**Comment by jayvdb** [comment]
Updated to use the default style, called `CodeFormatting`, not OTBS per https://github.com/pypa/virtualenv/issues/1371#issuecomment-505867590

**Comment by jayvdb** [comment]
It looks like the CI error isnt related to my changes.  Please correct me if I am wrong about that.

**Pull request merged**
