### PR TITLE
As an interim solution, suppress the warning that the imp module is d…

### PR DESCRIPTION
**Pull request by pfmoore**
…eprecated

### CODE REVIEW

**Comment by pfmoore** [comment]
@gaborbernat What's the failure here? It seems to be reporting lint problems on a load of files I didn't change :-(

**Comment by pfmoore** [comment]
Looks like master is also failing the same check. Am I therefore good to merge this?

**Comment by pfmoore** [comment]
@gaborbernat Can this go into 16.1? I know it's a bit last minute, but I hadn't realised no-one had addressed it till just now :-(

**Comment by gaborbernat** [comment]
@pfmoore sure.

**Comment by pfmoore** [comment]
Cool, thanks :-)

**Comment by gaborbernat** [comment]
@pfmoore ``virtualenv 16.1.0`` is out

**Pull request merged**
