### PR TITLE
Adding python-config script to virtualenv bin dir

### PR DESCRIPTION
**Pull request by madprog**
Should solve most of pypa/virtualenv#169

### CODE REVIEW

**Comment by amchoukir** [comment]
I can confirm that this patch fixes issues building [Valloric/ycmd](https://github.com/Valloric/ycmd)

**Comment by Ivoz** [comment]
It seems you've forgotten to add/commit the file `python-config` into git with this PR.

**Comment by madprog** [comment]
Hello Matt,
The python-config file is gzipped and base64-ed, and inlined at the line 2239 of virtualenv.py, just like activate_this.py or distutils.cfg
Where should it be copied else?

**Comment by Ivoz** [comment]
@madprog the source for all such files needs to live in [virtualenv_embedded](https://github.com/pypa/virtualenv/tree/develop/virtualenv_embedded). They should then be automatically included into `virtualenv.py` by running `bin/rebuild-script.py`.

**Comment by madprog** [comment]
Here is the commit with the missing file.

**Comment by Ivoz** [comment]
@madprog now I can see the contents of the file. It seems to me likely you copied this from a python 2 source. It uses the python 2 only print statement, so this is unsuitable to merge at the moment. Additionally, it doesn't cover the additional options available in a python3 `python-config`, you can see those [here for instance](https://github.com/python/cpython/blob/3.5/Misc/python-config.in).

**Comment by madprog** [comment]
@Ivoz Indeed it was at first copied from a python2-config. At that time (end of 2011), python3 was not *that* mainstream ;)
Please now find the python-config that you linked, updated so that it also runs with python2.
I compared the outputs using this zsh script:
```bash
#!/usr/bin/zsh

for i in prefix exec-prefix includes libs cflags ldflags extension-suffix help abiflags configdir; do
    echo "\x1b[32m$i\x1b[0m"

    PYTHON2_CMD="diff -u <(python2-config --$i 2>&1) <(python2 python-config --$i 2>&1)"
    PYTHON3_CMD="diff -u <(python3-config --$i 2>&1) <(python3 python-config --$i 2>&1)"

    if ! $SHELL -c "$PYTHON2_CMD" >/dev/null; then
        echo "\x1b[31mpython2\x1b[0m"
        $SHELL -c "$PYTHON2_CMD"
    fi

    if ! $SHELL -c "$PYTHON3_CMD" >/dev/null; then
        echo "\x1b[31mpython3\x1b[0m"
        $SHELL -c "$PYTHON3_CMD"
    fi
done
```
They are not exactly the same on my system: the order of the flags is different (but similar), some may be duplicated, and new flags are supported for python2, but I think that it "will do". What do you think?

**Comment by Ivoz** [comment]
@madprog I have applied this through #798, thanks for most of the work :)

**Pull request closed without merging**
