### PR TITLE
Fix use of _base_executable for Python 3.7.4

### PR DESCRIPTION
**Pull request by pfmoore**

### CODE REVIEW

**Comment by pfmoore** [comment]
Um, see my comment on #1380. I really think this needs testing at least once on a Python 3.7.4 system...

**Comment by fireundubh** [comment]
@pfmoore All `test_virtualenv` tests passed on Python 3.7.4 on Windows. I also did a real-world test and successfully created a Pipenv in PyCharm.

**Comment by pfmoore** [comment]
@fireundubh Fantastic, thanks for that :-)

**Comment by pradyunsg** [comment]
Hurrah! Thanks for this @pfmoore and @gjbernat!

**Pull request merged**
