### PR TITLE
Minor updates to the documentation

### PR DESCRIPTION
**Pull request by pradyunsg**
Miscellaneous updates following #1519.

Fixes typos, repeated words and inconsistent heading spacing
Repharses parts of the development documentation and CLI documentation.
Expands shorthands like "env var" and "config" to their full forms.
Uses descriptions from respective documentation, for projects listed in "related links".

Feel free to push additional changes to override these, since I'm gonna head to bed now.

### CODE REVIEW

**Comment by pradyunsg** [comment]
There are a few more issues that proselint identified, which we may/may not be worth addressing:

```
./docs/development.rst:125:34: after_the_deadline.redundancy Redundancy. Use 'facilitate' instead of 'facilitate easier'.
./docs/development.rst:152:6: consistency.spacing Inconsistent spacing after period (1 vs. 2 spaces).
./docs/development.rst:169:49: after_the_deadline.redundancy Redundancy. Use 'same' instead of 'exact same'.
./docs/development.rst:180:21: typography.symbols.ellipsis '...' is an approximation, use the ellipsis symbol '…'.
./docs/index.rst:35:13: needless_variants.misc Needless variant. 'extendable' is the preferred form.
./docs/index.rst:42:44: consistency.spacing Inconsistent spacing after period (1 vs. 2 spaces).
./docs/index.rst:45:80: consistency.spacing Inconsistent spacing after period (1 vs. 2 spaces).
./docs/user_guide.rst:45:44: weasel_words.very Substitute 'damn' every time you're inclined to write 'very'; your editor will delete it and the writing will be just as it should be. Found once elsewhere.
```

**Comment by gaborbernat** [comment]
I've made some small additions, but this is now ready to go once the CI passes.

thanks

**Comment by pradyunsg** [comment]
🥂 

You're *much* better at GIFs than I am. :P

**Comment by gaborbernat** [comment]
Note the latest rewrite branch doc is available under https://virtualenv.pypa.io/en/rewrite/index.html

**Pull request merged**
