### PR TITLE
Set VIRTUAL_ENV enviroment variable in activate_this.py

### PR DESCRIPTION
**Pull request by nonylene**
VIRTUAL_ENV was not set in activate_this.py, while set in other activate scripts.

### CODE REVIEW

**Comment by tgrant59** [comment]
👍

**Comment by nonylene** [comment]
Rebased against current master and ran `bin/rebuild_script.py` just now. (No changed)

**Comment by nonylene** [comment]
@pfmoore How about this pr?

**Comment by tgrant59** [comment]
@ssbarnea @gst This bug is causing us issues, do you think it could be merged soon?

**Comment by jcox-dev** [comment]
This would be nice to have in.

**Comment by hai-ld** [comment]
Could this PR be merged soon?

**Comment by ssbarnea** [comment]
@xavfernandez Thanks! I hope I will see more merges performed as current state of virtualenv is "kept in carbonite".

**Comment by nonylene** [comment]
@xavfernandez Thank you for response! I added a changelog in 86970de.

**Comment by nonylene** [comment]
CI failed, I'm checking now 👀

**Comment by nonylene** [comment]
```
setuptools requires Python '>=2.7,!=3.0.*,!=3.1.*,!=3.2.*' but the running Python is 2.6.6
ERROR: could not install deps [mock, pytest]; v = InvocationError('C:\\projects\\virtualenv\\.tox\\py\\Scripts\\pip.EXE install mock pytest (see C:\\projects\\virtualenv\\.tox\\py\\log\\py-1.log)', 1)
```

Oh, this is because setuptools dropped Python 2.6 support... https://github.com/pypa/setuptools/issues/878

This patch is not relevant to that issue, so ready to merge!

**Comment by pradyunsg** [comment]
You might want to merge master to fix the failing CI.

**Comment by nonylene** [comment]
Failed from the same reason. pytest also dropped 2.6 support today.

 https://github.com/pytest-dev/pytest/pull/2945

**Comment by twig** [comment]
This bug causes [newrelic-plugin-agent setup.py](https://github.com/MeetMe/newrelic-plugin-agent/blob/master/setup.py#L5) to fail because VIRTUAL_ENV isn't set when installing via [pipenv](https://github.com/pypa/pipenv/issues/829)

What's preventing this from being released?

**Comment by nonylene** [comment]
I resolved conflict. 

How about this pr? @gaborbernat

**Comment by nonylene** [comment]
Regression test added: ff51e55f8b1f885275376dc3023d71b390cbb5f7

(... and I've changed base commit to remove redundant merge commits.)

**Comment by nonylene** [comment]
Sorry but what does 'nm' mean?

**Comment by gaborbernat** [comment]
never mind 😀

**Comment by gaborbernat** [comment]
This now passes the bar of merge-ability. Thanks everyone for the patience, this will be part of the early January release.

**Comment by nonylene** [comment]
Thank you!

**Pull request merged**
