### PR TITLE
Revert the incorrect Windows part of #1388

### PR DESCRIPTION
**Pull request by pfmoore**
**NOTE** I ran `tox -e embed` to update the embedded file in `virtualenv.py`. It seems to have updated that file correctly, but the overall command failed:

```
>tox -e embed
embed create: C:\Work\Projects\virtualenv\.tox\embed
embed installdeps: pip >= 19.1.1
embed installed: virtualenv==16.6.0
embed run-test-pre: PYTHONHASHSEED='315'
embed run-test: commands[0] | python update_embedded.py
Found file site.py
  File up to date (crc: 788e6c21)
Found file activate.sh
  File up to date (crc: 0632d409)
Found file activate.fish
  File up to date (crc: a2df6828)
Found file activate.csh
  File up to date (crc: ff2bf2f5)
Found file activate.xsh
  File up to date (crc: fec22784)
Found file activate.bat
  File up to date (crc: 0f734cb0)
Found file deactivate.bat
  File up to date (crc: 9ddc164f)
Found file activate.ps1
  Content changed (crc: 135a527b -> 9b3db782)
Found file distutils-init.py
  File up to date (crc: affaad52)
Found file distutils.cfg
  File up to date (crc: cd607b02)
Found file activate_this.py
  File up to date (crc: e2ab3eed)
Found file python-config
  File up to date (crc: 9a7177a5)
Content updated; overwriting... done.
ERROR: InvocationError for command 'C:\Work\Projects\virtualenv\.tox\embed\Scripts\python.EXE' update_embedded.py (exited with code 1)
_________________________________________________________________________ summary _________________________________________________________________________
ERROR:   embed: commands failed
```

I don't know if this is an issue, as there's no useful information here about what the problem was. If there's a concern that this may have corrupted something, can someone just take the change to `activate.ps1` and make a new PR based on it?

### CODE REVIEW

**Comment by gaborbernat** [comment]
@pfmoore the command fails if it makes changes (this is so that CI will also fail if not everything is embedded already)

**Comment by pfmoore** [comment]
Ah, I see. Might be worth mentioning that in the development docs! Thanks for the quick response and merge :-)

**Comment by pfmoore** [comment]
Oh heck, never mind. It does say in the docs. My mistake for only skimming them. (My excuse is that I was trying to do this quickly, in a brief gap between other tasks. Sorry).

**Comment by gaborbernat** [comment]
no worries 👍

**Pull request merged**
