### PR TITLE
escape string in __VIRTUAL_ENV__ path for bash

### PR DESCRIPTION
**Pull request by davidbstein**
Fixes issue pypa/virtualenv#53 in bash and shell only. Uses the printf `%q` "shell quote" formatter. Falls back to quoting some characters that universally need to be escaped. 

Fallback is needed because while bash's `printf` command has the `%q` formatter, the builtin function printf may not.

(edit): removed irrelevant link

### CODE REVIEW

**Comment by Ivoz** [comment]
Hi there, you need to actually commit changes for virtualenv_embedded/activate.sh as well.

Did you understand *not* to do so from reading the documentation somewhere? If so we need to clarify it.

**Comment by davidbstein** [comment]
Hi Matt -

Completely my fault, have had a fix locally for a while and pushed it
upstream without checking contributing.rst - docs are quite clear. Sorry.

-David

On Sun, Oct 18, 2015 at 2:07 AM Matt Iversen <notifications@github.com>
wrote:

> Hi there, you need to actually commit changes for
> virtualenv_embedded/activate.sh as well.
>
> Did you understand *not* to do so from reading the documentation
> somewhere? If so we need to clarify it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pypa/virtualenv/pull/811#issuecomment-148994319>.
>
-- 

Sent from a phone.

**Comment by Ivoz** [comment]
Hi @davidbstein upon looking further, I don't see how this solves #53 at all?

**Comment by pfmoore** [comment]
Regardless of whether this PR does fix the problem, would it be worth adding a test that demonstrates the issue, so we'd at least be able to see the problem via a test?

**Comment by davidbstein** [comment]
thanks for the quick review!

@Ivoz - AFAICT, #53 is caused by the bad entry in PATH, not the malformed shebang - easy_install and pip work again with this change  (testing on Ubuntu and OSX - escaping the PATH fixes the issue, escaping the shebang line does not). Fixing the shebang line seems like a good idea - I'll try to dig into a good way to do that.

@pfmoore - tests seem like a great idea. Will add one.

**Comment by Ivoz** [comment]
@davidbstein so after manually applying your patch to test,

I created a new virtualenv called "h a", confirm the patch is in the new virtualenv:
```
(h\ a) ivo·ivosung ~/code/pypa/virtualenv/h a/bin develop $ cat activate | grep 'VIRTUAL_ENV='
# VIRTUAL_ENV="/home/ivo/code/pypa/virtualenv/h a"
VIRTUAL_ENV=$(printf %q "/home/ivo/code/pypa/virtualenv/h a") || VIRTUAL_ENV=$(echo "/home/ivo/code/pypa/virtualenv/h a" | sed 's/[ ()$;]/\\&/g')
```
Yes, we've managed to escape it in the `$PATH`:
```
(h\ a) ivo·ivosung ~/code/pypa/virtualenv/h a/bin develop $ echo $PATH
/home/ivo/code/pypa/virtualenv/h\ a/bin:/home/ivo/bin:/hom...
```
But, We can't escape the hashbang problem:
```
(h\ a) ivo·ivosung ~/code/pypa/virtualenv/h a/bin develop $ pip -h
/home/ivo/.pyenv/plugins/pyenv-pip-rehash/libexec/pip: ./pip: "/home/ivo/code/pypa/virtualenv/h\: bad interpreter: No such file or directory
 126 (h\ a) ivo·ivosung ~/code/pypa/virtualenv/h a/bin develop $ easy_install -h
/home/ivo/.pyenv/plugins/pyenv-pip-rehash/libexec/easy_install: ./easy_install: "/home/ivo/code/pypa/virtualenv/h: bad interpreter: No such file or directory
```

So we've put an escape in the `$VIRTUAL_ENV` env var & `$PATH`, but paths could be resolved without that anyway; and we haven't fixed execution of scripts as shown above. So we still haven't fixed scripts being broken, as is title of #53

**Comment by Ivoz** [comment]
I'm pretty sure that escaping paths in `$PATH` is in fact *incorrect*.

I'm guessing that this is only working for you (or, *appearing* to work), because now that your patch with the backslash escape has made the virtualenv path invalid, when you type `$ pip`, `$ easy_install` etc you are finding working executable, but they are the global executables - we obviously don't want those. If you type `$ ./bin/pip` you will still find the command breaking from the space in the hashbang.

**Pull request closed without merging**
