### PR TITLE
Modify activate.bat to remove forced space after --prompt arg

### LINKED ISSUE #1168: COSMETIC: On Windows, --prompt adds a space to the resulting prompt after its argument; doesn't add space on Linux
When creating a new virtualenv with the `--prompt` option, on Windows a space is automatically added between the `--prompt=` value and the tail of the prompt:

```
C:\temp>virtualenv env --prompt="(myenv)"
...

C:\temp>env\scripts\activate

(myenv) C:\temp> 
```

On Debian stretch, a space is not added:

```
me@mycomp:~$ virtualenv env --prompt="(myenv)"
...

me@mycomp:~$ source env/bin/activate

(myenv)me@mycomp:~$ 
```

If auto-insertion of a space is desired behavior, it should be a simple fix: adding a space [here in `activate.sh`](https://github.com/pypa/virtualenv/blob/2f5c75bd4762463e904aa1c06ccba29dd817e940/virtualenv_embedded/activate.sh#L59), before the `$PS1`.

If this is desired, I can create a PR.

-----

**EDIT:** Per discussion below, the decision has been made to ***remove*** the mandatory space after the custom prompt string, for all shells.

### PR DESCRIPTION
**Pull request by bskinn**
Fixes #1168, per the approach suggested there (**BUT SEE BELOW**).

~~The `tasks/update_embedded.py` script has been run, updating
`virtualenv.py`.~~

~~A local test virtual environment created after implementing the change
does show the desired space between the virtualenv `--prompt`
argument and the old `$PS1` portion of the prompt.~~

Per discussion under #1168, this PR will now **REMOVE** forced spaces added after custom prompt prefixes as specified via `--prompt`. Only `activate.bat` required changes; these changes were embedded into `virtualenv.py` via `tox -e embed`.

## Thanks for contributing a pull request, see checklist all is good!

- [x] wrote descriptive pull request text
- [ ] added/updated test(s) 
- [x] updated/extended the documentation **[N/A]**
- [ ] added news fragment in ``docs/changelog`` folder

### CODE REVIEW

**Comment by bskinn** [comment]
> I would like test for this, just to avoid regression. Thanks!

<nod>, can do. I should also be able to add a similar test for Windows `cmd`.

I'm not familiar with the other shells -- should they have similar tests as well?

Also, I'll fix that `:user:` directive that's raising the warning in the docs test.

**Comment by gaborbernat** [comment]
I've fixed on master now 😁

**Comment by bskinn** [comment]
Ok, @gaborbernat, after taking a closer look at all of the `activate.xyz` scripts, it seems like there's potentially a *lot* of work to do in order to bring their behavior into consistency.  I created a Project on my fork to try to organize the info on where things stand; in particular, check out [this column](https://github.com/bskinn/virtualenv/projects/1#column-4207530).

How deep down the rabbit hole should I go on this?

**Comment by gaborbernat** [comment]
Sounds great.

**Comment by bskinn** [comment]
This PR is obsolete now; closing.

**Pull request closed without merging**
