### PR TITLE
Fix #2728: Activating venv create unwanted console output 

### LINKED ISSUE #2728: Activating venv create unwanted console output
**Issue**
Activating venv shouldn't generate any output. In versions above 20.25.1 it prints `()` on activation.

20.25.1:
```console
C:\projects\pythontests>venv\Scripts\activate.bat

(venv) C:\projects\pythontests>
```
20.25.2 (same effect in the latest version)
```console
C:\projects\pythontests>venv\Scripts\activate.bat

C:\projects\pythontests>()
```

**Environment**

Provide at least:

- OS: Windows 10, Windows 11
- `pip list` of the host python where `virtualenv` is installed:

```console
Package      Version
distlib      0.3.8
filelock     3.14.0
pip          22.0.4
platformdirs 4.2.2
setuptools   58.1.0
virtualenv   20.25.2
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:
20.25.1
```console
C:\projects\pythontests>python -m virtualenv -vvv --with-traceback env
417 setup logging to NOTSET [DEBUG report:37]
565 find interpreter for spec PythonSpec(path=C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\python.exe) [INFO builtin:58]
565 proposed PythonInfo(spec=CPython3.9.12.final.0-64, exe=C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\python.exe, platform=win32, version='3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [INFO builtin:65]
568 accepted PythonInfo(spec=CPython3.9.12.final.0-64, exe=C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\python.exe, platform=win32, version='3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [DEBUG builtin:67]
580 symlink on filesystem does not work [DEBUG info:44]
580 filesystem is not case-sensitive [DEBUG info:25]
702 create virtual environment via CPython3Windows(dest=C:\projects\pythontests\env, clear=False, no_vcs_ignore=False, global=False) [INFO session:50]
702 create folder C:\projects\pythontests\env\Lib\site-packages [DEBUG _sync:12]
706 create folder C:\projects\pythontests\env\Scripts [DEBUG _sync:12]
708 write C:\projects\pythontests\env\pyvenv.cfg [DEBUG pyenv_cfg:33]
708     home = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39 [DEBUG pyenv_cfg:38]
708     implementation = CPython [DEBUG pyenv_cfg:38]
708     version_info = 3.9.12.final.0 [DEBUG pyenv_cfg:38]
708     virtualenv = 20.25.1 [DEBUG pyenv_cfg:38]
710     include-system-site-packages = false [DEBUG pyenv_cfg:38]
710     base-prefix = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39 [DEBUG pyenv_cfg:38]
711     base-exec-prefix = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39 [DEBUG pyenv_cfg:38]
711     base-executable = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\python.exe [DEBUG pyenv_cfg:38]
713 copy C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\Lib\venv\scripts\nt\python.exe to C:\projects\pythontests\env\Scripts\python.exe [DEBUG _sync:40]
717 copy C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\Lib\venv\scripts\nt\pythonw.exe to C:\projects\pythontests\env\Scripts\pythonw.exe [DEBUG _sync:40]
717 create virtualenv import hook file C:\projects\pythontests\env\Lib\site-packages\_virtualenv.pth [DEBUG api:91]
717 create C:\projects\pythontests\env\Lib\site-packages\_virtualenv.py [DEBUG api:94]
717 ============================== target debug ============================== [DEBUG session:52]
725 debug via 'C:\projects\pythontests\env\Scripts\python.exe' 'C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\lib\site-packages\virtualenv\create\debug.py' [DEBUG creator:200]
725 {
  "sys": {
    "executable": "C:\\projects\\pythontests\\env\\Scripts\\python.exe",
    "_base_executable": "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39\\python.exe",
    "prefix": "C:\\projects\\pythontests\\env",
    "base_prefix": "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39",
    "real_prefix": null,
    "exec_prefix": "C:\\projects\\pythontests\\env",
    "base_exec_prefix": "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39",
    "path": [
      "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip",
      "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39\\DLLs",
      "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39\\lib",
      "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39",
      "C:\\projects\\pythontests\\env",
      "C:\\projects\\pythontests\\env\\lib\\site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "cp1252"
  },
  "version": "3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]",
  "makefile_filename": "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\config\\Makefile",
  "os": "<module 'os' from 'C:\\\\Users\\\\PNalepka\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib\\\\os.py'>",
  "site": "<module 'site' from 'C:\\\\Users\\\\PNalepka\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib\\\\site.py'>",
  "datetime": "<module 'datetime' from 'C:\\\\Users\\\\PNalepka\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib\\\\datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from 'C:\\\\Users\\\\PNalepka\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib\\\\json\\\\__init__.py'>"
} [DEBUG session:53]
1065 add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\PNalepka\AppData\Local\pypa\virtualenv) [INFO session:57]
1073 got embed update of distribution %s from ('pip', WindowsPath('C:/Users/PNalepka/AppData/Local/pypa/virtualenv/wheel/3.9/embed/3/pip.json')) [DEBUG via_disk_folder:131]
1073 got embed update of distribution %s from ('setuptools', WindowsPath('C:/Users/PNalepka/AppData/Local/pypa/virtualenv/wheel/3.9/embed/3/setuptools.json')) [DEBUG via_disk_folder:131]
1073 got embed update of distribution %s from ('wheel', WindowsPath('C:/Users/PNalepka/AppData/Local/pypa/virtualenv/wheel/3.9/embed/3/wheel.json')) [DEBUG via_disk_folder:131]
1073 got embed update of distribution %s from ('pip', WindowsPath('C:/Users/PNalepka/AppData/Local/pypa/virtualenv/wheel/3.9/embed/3/pip.json')) [DEBUG via_disk_folder:131]
1073 got embed update of distribution %s from ('setuptools', WindowsPath('C:/Users/PNalepka/AppData/Local/pypa/virtualenv/wheel/3.9/embed/3/setuptools.json')) [DEBUG via_disk_folder:131]
1073 got embed update of distribution %s from ('wheel', WindowsPath('C:/Users/PNalepka/AppData/Local/pypa/virtualenv/wheel/3.9/embed/3/wheel.json')) [DEBUG via_disk_folder:131]
1073 install pip from wheel C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\lib\site-packages\virtualenv\seed\wheels\embed\pip-24.0-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
1073 install setuptools from wheel C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\lib\site-packages\virtualenv\seed\wheels\embed\setuptools-69.1.0-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
1073 install wheel from wheel C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\lib\site-packages\virtualenv\seed\wheels\embed\wheel-0.42.0-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
1081 Attempting to acquire lock 1969660185328 on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any.lock [DEBUG _api:294]
1081 Attempting to acquire lock 1969660185040 on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.1.0-py3-none-any.lock [DEBUG _api:294]
1081 Attempting to acquire lock 1969660184704 on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.42.0-py3-none-any.lock [DEBUG _api:294]
1082 Lock 1969660185328 acquired on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any.lock [DEBUG _api:297]
1083 Attempting to release lock 1969660185328 on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any.lock [DEBUG _api:327]
1083 Lock 1969660184704 acquired on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.42.0-py3-none-any.lock [DEBUG _api:297]
1083 Lock 1969660185040 acquired on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.1.0-py3-none-any.lock [DEBUG _api:297]
1083 Lock 1969660185328 released on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any.lock [DEBUG _api:330]
1083 Attempting to release lock 1969660184704 on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.42.0-py3-none-any.lock [DEBUG _api:327]
1083 Attempting to release lock 1969660185040 on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.1.0-py3-none-any.lock [DEBUG _api:327]
1083 Lock 1969660184704 released on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.42.0-py3-none-any.lock [DEBUG _api:330]
1083 Lock 1969660185040 released on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.1.0-py3-none-any.lock [DEBUG _api:330]
1085 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any\pip to C:\projects\pythontests\env\Lib\site-packages\pip [DEBUG _sync:40]
1085 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.42.0-py3-none-any\wheel to C:\projects\pythontests\env\Lib\site-packages\wheel [DEBUG _sync:40]
1085 copy C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.1.0-py3-none-any\distutils-precedence.pth to C:\projects\pythontests\env\Lib\site-packages\distutils-precedence.pth [DEBUG _sync:40]
1089 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.1.0-py3-none-any\pkg_resources to C:\projects\pythontests\env\Lib\site-packages\pkg_resources [DEBUG _sync:40]
1157 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.42.0-py3-none-any\wheel-0.42.0.dist-info to C:\projects\pythontests\env\Lib\site-packages\wheel-0.42.0.dist-info [DEBUG _sync:40]
1174 copy C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.42.0-py3-none-any\wheel-0.42.0.virtualenv to C:\projects\pythontests\env\Lib\site-packages\wheel-0.42.0.virtualenv [DEBUG _sync:40]
1184 generated console scripts wheel3.9.exe wheel-3.9.exe wheel3.exe wheel.exe [DEBUG base:43]
1200 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.1.0-py3-none-any\setuptools to C:\projects\pythontests\env\Lib\site-packages\setuptools [DEBUG _sync:40]
1568 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.1.0-py3-none-any\setuptools-69.1.0.dist-info to C:\projects\pythontests\env\Lib\site-packages\setuptools-69.1.0.dist-info [DEBUG _sync:40]
1616 copy C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.1.0-py3-none-any\setuptools-69.1.0.virtualenv to C:\projects\pythontests\env\Lib\site-packages\setuptools-69.1.0.virtualenv [DEBUG _sync:40]
1630 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.1.0-py3-none-any\_distutils_hack to C:\projects\pythontests\env\Lib\site-packages\_distutils_hack [DEBUG _sync:40]
1658 generated console scripts  [DEBUG base:43]
2186 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any\pip-24.0.dist-info to C:\projects\pythontests\env\Lib\site-packages\pip-24.0.dist-info [DEBUG _sync:40]
2209 copy C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any\pip-24.0.virtualenv to C:\projects\pythontests\env\Lib\site-packages\pip-24.0.virtualenv [DEBUG _sync:40]
2218 generated console scripts pip3.9.exe pip3.exe pip.exe pip-3.9.exe [DEBUG base:43]
2219 add activators for Bash, Batch, Fish, Nushell, PowerShell, Python [INFO session:63]
2226 write C:\projects\pythontests\env\pyvenv.cfg [DEBUG pyenv_cfg:33]
2226    home = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39 [DEBUG pyenv_cfg:38]
2226    implementation = CPython [DEBUG pyenv_cfg:38]
2226    version_info = 3.9.12.final.0 [DEBUG pyenv_cfg:38]
2226    virtualenv = 20.25.1 [DEBUG pyenv_cfg:38]
2226    include-system-site-packages = false [DEBUG pyenv_cfg:38]
2226    base-prefix = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39 [DEBUG pyenv_cfg:38]
2232    base-exec-prefix = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39 [DEBUG pyenv_cfg:38]
2232    base-executable = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\python.exe [DEBUG pyenv_cfg:38]
2232 created virtual environment CPython3.9.12.final.0-64 in 1832ms
  creator CPython3Windows(dest=C:\projects\pythontests\env, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\PNalepka\AppData\Local\pypa\virtualenv)
    added seed packages: pip==24.0, setuptools==69.1.0, wheel==0.42.0
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator [WARNING __main__:19]
```
20.25.2:
```console
C:\projects\pythontests>python -m virtualenv -vvv --with-traceback venv
470 setup logging to NOTSET [DEBUG report:36]
576 find interpreter for spec PythonSpec(path=C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\python.exe) [INFO builtin:58]
576 proposed PythonInfo(spec=CPython3.9.12.final.0-64, exe=C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\python.exe, platform=win32, version='3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [INFO builtin:65]
576 accepted PythonInfo(spec=CPython3.9.12.final.0-64, exe=C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\python.exe, platform=win32, version='3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]', encoding_fs_io=utf-8-utf-8) [DEBUG builtin:67]
584 symlink on filesystem does not work [DEBUG info:44]
584 filesystem is not case-sensitive [DEBUG info:25]
681 create virtual environment via CPython3Windows(dest=C:\projects\pythontests\venv, clear=False, no_vcs_ignore=False, global=False) [INFO session:50]
681 create folder C:\projects\pythontests\venv\Lib\site-packages [DEBUG _sync:12]
681 create folder C:\projects\pythontests\venv\Scripts [DEBUG _sync:12]
689 write C:\projects\pythontests\venv\pyvenv.cfg [DEBUG pyenv_cfg:33]
689     home = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39 [DEBUG pyenv_cfg:38]
689     implementation = CPython [DEBUG pyenv_cfg:38]
689     version_info = 3.9.12.final.0 [DEBUG pyenv_cfg:38]
689     virtualenv = 20.25.2 [DEBUG pyenv_cfg:38]
689     include-system-site-packages = false [DEBUG pyenv_cfg:38]
689     base-prefix = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39 [DEBUG pyenv_cfg:38]
689     base-exec-prefix = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39 [DEBUG pyenv_cfg:38]
689     base-executable = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\python.exe [DEBUG pyenv_cfg:38]
689 copy C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\Lib\venv\scripts\nt\python.exe to C:\projects\pythontests\venv\Scripts\python.exe [DEBUG _sync:40]
697 copy C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\Lib\venv\scripts\nt\pythonw.exe to C:\projects\pythontests\venv\Scripts\pythonw.exe [DEBUG _sync:40]
705 create virtualenv import hook file C:\projects\pythontests\venv\Lib\site-packages\_virtualenv.pth [DEBUG api:91]
705 create C:\projects\pythontests\venv\Lib\site-packages\_virtualenv.py [DEBUG api:94]
713 ============================== target debug ============================== [DEBUG session:52]
713 debug via 'C:\projects\pythontests\venv\Scripts\python.exe' 'C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\lib\site-packages\virtualenv\create\debug.py' [DEBUG creator:200]
713 {
  "sys": {
    "executable": "C:\\projects\\pythontests\\venv\\Scripts\\python.exe",
    "_base_executable": "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39\\python.exe",
    "prefix": "C:\\projects\\pythontests\\venv",
    "base_prefix": "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39",
    "real_prefix": null,
    "exec_prefix": "C:\\projects\\pythontests\\venv",
    "base_exec_prefix": "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39",
    "path": [
      "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39\\python39.zip",
      "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39\\DLLs",
      "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39\\lib",
      "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39",
      "C:\\projects\\pythontests\\venv",
      "C:\\projects\\pythontests\\venv\\lib\\site-packages"
    ],
    "meta_path": [
      "<class '_virtualenv._Finder'>",
      "<class '_frozen_importlib.BuiltinImporter'>",
      "<class '_frozen_importlib.FrozenImporter'>",
      "<class '_frozen_importlib_external.PathFinder'>"
    ],
    "fs_encoding": "utf-8",
    "io_encoding": "cp1252"
  },
  "version": "3.9.12 (tags/v3.9.12:b28265d, Mar 23 2022, 23:52:46) [MSC v.1929 64 bit (AMD64)]",
  "makefile_filename": "C:\\Users\\PNalepka\\AppData\\Local\\Programs\\Python\\Python39\\Lib\\config\\Makefile",
  "os": "<module 'os' from 'C:\\\\Users\\\\PNalepka\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib\\\\os.py'>",
  "site": "<module 'site' from 'C:\\\\Users\\\\PNalepka\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib\\\\site.py'>",
  "datetime": "<module 'datetime' from 'C:\\\\Users\\\\PNalepka\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib\\\\datetime.py'>",
  "math": "<module 'math' (built-in)>",
  "json": "<module 'json' from 'C:\\\\Users\\\\PNalepka\\\\AppData\\\\Local\\\\Programs\\\\Python\\\\Python39\\\\lib\\\\json\\\\__init__.py'>"
} [DEBUG session:53]
1089 add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\PNalepka\AppData\Local\pypa\virtualenv) [INFO session:57]
1089 got embed update of distribution %s from ('pip', WindowsPath('C:/Users/PNalepka/AppData/Local/pypa/virtualenv/wheel/3.9/embed/3/pip.json')) [DEBUG via_disk_folder:131]
1089 got embed update of distribution %s from ('wheel', WindowsPath('C:/Users/PNalepka/AppData/Local/pypa/virtualenv/wheel/3.9/embed/3/wheel.json')) [DEBUG via_disk_folder:131]
1093 got embed update of distribution %s from ('setuptools', WindowsPath('C:/Users/PNalepka/AppData/Local/pypa/virtualenv/wheel/3.9/embed/3/setuptools.json')) [DEBUG via_disk_folder:131]
1101 got embed update of distribution %s from ('setuptools', WindowsPath('C:/Users/PNalepka/AppData/Local/pypa/virtualenv/wheel/3.9/embed/3/setuptools.json')) [DEBUG via_disk_folder:131]
1101 got embed update of distribution %s from ('pip', WindowsPath('C:/Users/PNalepka/AppData/Local/pypa/virtualenv/wheel/3.9/embed/3/pip.json')) [DEBUG via_disk_folder:131]
1101 got embed update of distribution %s from ('wheel', WindowsPath('C:/Users/PNalepka/AppData/Local/pypa/virtualenv/wheel/3.9/embed/3/wheel.json')) [DEBUG via_disk_folder:131]
1101 install setuptools from wheel C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\lib\site-packages\virtualenv\seed\wheels\embed\setuptools-69.5.1-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
1101 install pip from wheel C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\lib\site-packages\virtualenv\seed\wheels\embed\pip-24.0-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
1104 install wheel from wheel C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\lib\site-packages\virtualenv\seed\wheels\embed\wheel-0.43.0-py3-none-any.whl via CopyPipInstall [DEBUG via_app_data:49]
1104 Attempting to acquire lock 3035386235680 on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.5.1-py3-none-any.lock [DEBUG _api:294]
1105 Attempting to acquire lock 3035386235920 on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any.lock [DEBUG _api:294]
1105 Attempting to acquire lock 3035386235152 on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.43.0-py3-none-any.lock [DEBUG _api:294]
1106 Lock 3035386235680 acquired on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.5.1-py3-none-any.lock [DEBUG _api:297]
1106 Lock 3035386235920 acquired on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any.lock [DEBUG _api:297]
1106 Lock 3035386235152 acquired on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.43.0-py3-none-any.lock [DEBUG _api:297]
1107 Attempting to release lock 3035386235680 on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.5.1-py3-none-any.lock [DEBUG _api:327]
1107 Attempting to release lock 3035386235920 on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any.lock [DEBUG _api:327]
1107 Attempting to release lock 3035386235152 on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.43.0-py3-none-any.lock [DEBUG _api:327]
1107 Lock 3035386235680 released on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.5.1-py3-none-any.lock [DEBUG _api:330]
1107 Lock 3035386235920 released on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any.lock [DEBUG _api:330]
1108 Lock 3035386235152 released on C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.43.0-py3-none-any.lock [DEBUG _api:330]
1110 copy C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.5.1-py3-none-any\distutils-precedence.pth to C:\projects\pythontests\venv\Lib\site-packages\distutils-precedence.pth [DEBUG _sync:40]
1110 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any\pip to C:\projects\pythontests\venv\Lib\site-packages\pip [DEBUG _sync:40]
1110 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.43.0-py3-none-any\wheel to C:\projects\pythontests\venv\Lib\site-packages\wheel [DEBUG _sync:40]
1120 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.5.1-py3-none-any\pkg_resources to C:\projects\pythontests\venv\Lib\site-packages\pkg_resources [DEBUG _sync:40]
1904 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.43.0-py3-none-any\wheel-0.43.0.dist-info to C:\projects\pythontests\venv\Lib\site-packages\wheel-0.43.0.dist-info [DEBUG _sync:40]
1981 copy C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\wheel-0.43.0-py3-none-any\wheel-0.43.0.virtualenv to C:\projects\pythontests\venv\Lib\site-packages\wheel-0.43.0.virtualenv [DEBUG _sync:40]
1994 generated console scripts wheel3.exe wheel3.9.exe wheel-3.9.exe wheel.exe [DEBUG base:43]
2074 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any\pip-24.0.dist-info to C:\projects\pythontests\venv\Lib\site-packages\pip-24.0.dist-info [DEBUG _sync:40]
2092 copy C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\pip-24.0-py3-none-any\pip-24.0.virtualenv to C:\projects\pythontests\venv\Lib\site-packages\pip-24.0.virtualenv [DEBUG _sync:40]
2105 generated console scripts pip.exe pip3.9.exe pip3.exe pip-3.9.exe [DEBUG base:43]
2704 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.5.1-py3-none-any\setuptools to C:\projects\pythontests\venv\Lib\site-packages\setuptools [DEBUG _sync:40]
8728 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.5.1-py3-none-any\setuptools-69.5.1.dist-info to C:\projects\pythontests\venv\Lib\site-packages\setuptools-69.5.1.dist-info [DEBUG _sync:40]
8859 copy C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.5.1-py3-none-any\setuptools-69.5.1.virtualenv to C:\projects\pythontests\venv\Lib\site-packages\setuptools-69.5.1.virtualenv [DEBUG _sync:40]
8869 copy directory C:\Users\PNalepka\AppData\Local\pypa\virtualenv\wheel\3.9\image\1\CopyPipInstall\setuptools-69.5.1-py3-none-any\_distutils_hack to C:\projects\pythontests\venv\Lib\site-packages\_distutils_hack [DEBUG _sync:40]
8894 generated console scripts  [DEBUG base:43]
8894 add activators for Bash, Batch, Fish, Nushell, PowerShell, Python [INFO session:63]
9078 write C:\projects\pythontests\venv\pyvenv.cfg [DEBUG pyenv_cfg:33]
9084    home = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39 [DEBUG pyenv_cfg:38]
9084    implementation = CPython [DEBUG pyenv_cfg:38]
9084    version_info = 3.9.12.final.0 [DEBUG pyenv_cfg:38]
9084    virtualenv = 20.25.2 [DEBUG pyenv_cfg:38]
9084    include-system-site-packages = false [DEBUG pyenv_cfg:38]
9086    base-prefix = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39 [DEBUG pyenv_cfg:38]
9086    base-exec-prefix = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39 [DEBUG pyenv_cfg:38]
9086    base-executable = C:\Users\PNalepka\AppData\Local\Programs\Python\Python39\python.exe [DEBUG pyenv_cfg:38]
9086 created virtual environment CPython3.9.12.final.0-64 in 8630ms
  creator CPython3Windows(dest=C:\projects\pythontests\venv, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\PNalepka\AppData\Local\pypa\virtualenv)
    added seed packages: pip==24.0, setuptools==69.5.1, wheel==0.43.0
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator [WARNING __main__:19]
```

### PR DESCRIPTION
**Pull request by ShootGan**
### Thanks for contributing, make sure you address all the checklists (for details on how see [development documentation](https://virtualenv.pypa.io/en/latest/development.html#development))
Fix problem related with #2728 

- [x ] ran the linter to address style issues (`tox -e fix`)
- [x ] wrote descriptive pull request text
- [x ] ensured there are test(s) validating the fix
- [x ] added news fragment in `docs/changelog` folder
- [x ] updated/extended the documentation

### CODE REVIEW

**Review by gaborbernat — CHANGES_REQUESTED** [review]
test please

**Comment by ShootGan** [comment]
@gaborbernat do you mean I should write a test for this change?

**Comment by gaborbernat** [comment]
Yes.

**Comment by ShootGan** [comment]
So I need help with testing. I can't figure out how tests works in this project.

**Pull request merged**
