### PR TITLE
Further fix for #1339 (--python option)

### PR DESCRIPTION
**Pull request by pfmoore**

### CODE REVIEW

**Comment by pfmoore** [comment]
Hmm, I'm getting test errors saying "ERROR: target path contains the operating system path separator ';'". That doesn't seem related to my change (and I think there was a recent change merged to do with that). So is there some other issue with master? @gaborbernat 

Having said that, there do seem to be some issues with my code - but I'm not clear what yet. I'm working on those :-)

**Comment by pfmoore** [comment]
Thanks for the fast merge!

**Comment by gaborbernat** [comment]
I thank you for the fast fix. Release will take a week or two as I'm in middle of multiple major changes. Will be inside release 17.0.0 though 😁

**Comment by pfmoore** [comment]
No worries, it's been hitting me personally, so I was well motivated to find a fix :-) And I can use the version from github until the release arrives, so we're good there.

**Comment by gaborbernat** [comment]
FYI will move to src layout soon, so use pep-517+518 to install from GitHub 😁

**Comment by asottile** [comment]
Awesome, just did some debugging / spelunking to find this solves the issue I'm seeing as well in https://github.com/pre-commit/pre-commit/issues/1046

looking forward to the release!

fwiw my reproduction was a little more involved for whatever reason:

```
python -mvirtualenv venv2 -p 'C:\Users\Anthony\AppData\Local\Temp\t\x\vvv\Scripts\python.exe'
```

**Comment by gaborbernat** [comment]
I'll release tomorrow as a patch release 👌

**Pull request merged**
