### PR TITLE
?? prompt should be wrapped in paranthesis ??

### PR DESCRIPTION
**Pull request by tusharsadhwani**
### Thanks for contributing, make sure you address all the checklists (for details on how see
[development documentation](https://virtualenv.pypa.io/en/latest/development.html#development))!

- [x] ran the linter to address style issues (``tox -e fix_lint``)
- [x] wrote descriptive pull request text
- [x] ensured there are test(s) validating the fix
- [x] added news fragment in ``docs/changelog`` folder
- [x] updated/extended the documentation

---

This adds brackets and a space around the prompt text, in the case of `--prompt=.`

Previous behaviour:

```console
$ pwd
/code/myproject

$ virtualenv venv --prompt .
[...]
$ . venv/bin/activate
myproject$ 
```

New behaviour:
```console
$ virtualenv venv --prompt .
[...]
$ . venv/bin/activate
(myproject) $ 
```

---

This is a super trivial change, should I make a news fragment for this?

### CODE REVIEW

**Comment by tusharsadhwani** [comment]
Sorry for testing everything on CI, but it all works now.

Weirdly though, the `test_fish[no_prompt]` test is failing on CI while it works fine locally.

**Comment by gaborbernat** [comment]
> Sorry for testing everything on CI, but it all works now.
> 
> Weirdly though, the `test_fish[no_prompt]` test is failing on CI while it works fine locally.

The CI is the true judge of everything works fine 😃 so you'll need to fix the CI for this to be ready to review 🙏

**Comment by tusharsadhwani** [comment]
@gaborbernat All done, PTAL :)

**Review by gaborbernat — COMMENTED** [review]
Looks good the only thing remaining is a changelog entry, as a feature, announcing the change in behaviour.

**Comment by tusharsadhwani** [comment]
It's crazy that some of these checks take 60-90 mins to run. There must be a better way 🤔

But anyway, doc entry has also been added, hopefully I did it right.

**Comment by tusharsadhwani** [comment]
It's crazy that some of these checks take 60-90 mins to run. There must be a better way 🤔

But anyway, doc entry has also been added, hopefully I did it right.

**Comment by gaborbernat** [comment]
> It's crazy that some of these checks take 60-90 mins to run. There must be a better way

Not that I'm aware so if you have suggestions don't hold back.

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
