### PR TITLE
Add initial IronPython support

### PR DESCRIPTION
**Pull request by slozier**

### CODE REVIEW

**Comment by gaborbernat** [comment]
this will need to wait and use the new rewrite interface, should be a few more weeks only 😀

**Comment by slozier** [comment]
@gaborbernat No problem, just trying to get the ball rolling again since someone asked about this on gitter. 😄

**Comment by gaborbernat** [comment]
I'll reach out to you as soon as we release the rewrite 😁

**Comment by gaborbernat** [comment]
Closing this until the rewrite completes, we can open a new PR against that.

**Comment by gaborbernat** [comment]
With virtualenv 20 it's now possible to define custom interpreters via https://virtualenv.pypa.io/en/latest/extend.html#creators, I encourage you to use this and create virtualenv-ironpython package 👍

**Pull request closed without merging**
