### PR TITLE
Added space between virtualenv folder name and old PS1 string to make resulting PS1 more clean.

### PR DESCRIPTION
**Pull request by phpdude**
Added space between virtualenv folder name and old PS1 string to make resulting PS1 more clean.

Was

    (test)@dude /Users/WWW/GitHub#

And now

    (test) @dude /Users/WWW/GitHub#

What you think about this improvement?

### CODE REVIEW

**Comment by jacquerie** [comment]
:+1:

Right now I have to edit the `bin/activate` file in each virtualenv, this will save me a little time.

**Comment by Sinkler** [comment]
:+1:

**Comment by adw0rd** [comment]
:+1:

**Comment by Koshub** [comment]
:+1:

**Comment by epsyl** [comment]
:+1:

**Comment by studentIvan** [comment]
+1

**Comment by Ivoz** [comment]
Cheers, I applied this manually in 7905ddecf91ba91633a18b9652284c03f9417d65

**Comment by Sinkler** [comment]
:+1:

**Comment by phpdude** [comment]
Nice. Thank you!

**Comment by Koshub** [comment]
:+1:

**Pull request closed without merging**
