### PR TITLE
Upgrade to pip 20.1.1

### PR DESCRIPTION
**Pull request by gaborbernat**

### CODE REVIEW

**Comment by pradyunsg** [comment]
Retitled to get the version right. :)

**Comment by gaborbernat** [comment]
thanks 👍

**Comment by gaborbernat** [comment]
@pradyunsg We'll hold off the release until tomorrow evening to give time to people to discover any major bugs within pip, and hold off the release if they do fine. Can you ping back here tomorrow if you think we can proceed or not?

**Comment by pradyunsg** [comment]
Sure, works for me! In case I don't say anything, assume all is well. :)

**Pull request merged**
