### PR TITLE
Do not override certificate bundle if it is defined in pip config

### PR DESCRIPTION
**Pull request by daa**
## Keep certificate option if it is set in pip config file or environment variable

This is one possible approach to solve #1260: script wrapping ``pip`` invocation first loads configuration and checks if ``cert`` option is defined there, and if it is defined does not override it with ``--cert`` command line argument.

I'd like to know your opinion on it. Personally I'm not very fond of depending on ``pip``'s internal modules but it should not be a big problem as ``virtualenv`` bundles and uses ``pip`` wheel of known version.

- [x] wrote descriptive pull request text
- [x] added/updated test(s)
- [ ] updated/extended the documentation
- [x] added news fragment in ``docs/changelog`` folder

### CODE REVIEW

**Comment by spikerobinsonDLG** [comment]
This may have created a wider problem that --cert is never honoured, if the config file sets a value for cert? Was that intended / expected? I think I'm seeing that behaviour, that --cert is ignored in general, not just in the intended context (a new installation within virtualenv).

**Comment by spikerobinsonDLG** [comment]
Specifically what is happening in my case is that the curl environment variable CURL_CA_BUNDLE is overriding the pip --cert setting. I can prove this by changing the CURL_CA_BUNDLE value and the behaviour of pip (with or without --cert) immediately changes. It suggests there is an inheritance where PIP_CERT inherits from CURL_CA_BUNDLE if that is set? In turn, the effect of this patch (#1273) is that the environment variable overrides the command line switch (--cert). I don't think this is desirable behaviour in the general case, outside of the special case of installing inside virtualenv.

**Comment by gaborbernat** [comment]
This PR is for an old no longer maintained version of virtualenv.

**Comment by daa** [comment]
Most likely it's an effect of ``requests`` using ``CURL_CA_BUNDLE`` to find the list of trusted CAs: https://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification. More specifically such behaviour is defined at https://github.com/psf/requests/blob/master/requests/sessions.py#L50-L67 and https://github.com/psf/requests/blob/master/requests/sessions.py#L717-L724

**Comment by spikerobinsonDLG** [comment]
> This PR is for an old no longer maintained version of virtualenv.

Ah sorry I had misunderstood that. If this PR was only scoped to virtualenv and did not affect pip in general then probably my issue lies elsewhere.

**Comment by gaborbernat** [comment]
This PR was scoped at an old version of virtualenv <16, version 20+ is a total rewrite so anything you see here is not relevant there.

**Comment by spikerobinsonDLG** [comment]
> Most likely it's an effect of `requests` using `CURL_CA_BUNDLE` to find the list of trusted CAs: https://docs.python-requests.org/en/master/user/advanced/#ssl-cert-verification. More specifically such behaviour is defined at https://github.com/psf/requests/blob/master/requests/sessions.py#L50-L67 and https://github.com/psf/requests/blob/master/requests/sessions.py#L717-L724

Thanks for those references, much appreciated. Your refs make it clear that CURL_CA_BUNDLE is used if REQUESTS_CA_BUNDLE is empty.  I am still left wondering why --cert commandline switch in pip seems to be overriden by these environment variables.

Is the simple answer that I am using conda activate, and conda activate uses virtualenv under the hood?

**Comment by spikerobinsonDLG** [comment]
Thanks for the help. It looks like I am commenting in the wrong place - I will try to get myself to the correct repo and comment there. I appreciate your patience!

**Comment by daa** [comment]
``pip`` uses ``requests`` for HTTP communication.

**Pull request merged**
