### PR TITLE
BUG: pypy dlls are named differently

### PR DESCRIPTION
**Pull request by mattip**
fixes issue #794, in use on the pypy win32 buildbot

### CODE REVIEW

**Comment by mattip** [comment]
ping

**Comment by pradyunsg** [comment]
Hi @mattip! Thanks for the PR!

I would have reviewed this but I'm not very familiar with the details of pypy so... yeah.

The maintainers are basically overworked volunteers so, it usually takes a (fair) bit of time for someone to come around to reviewing PRs.

Thanks for being patient! :)

**Comment by mattip** [comment]
@pradyunsg I understand, and thanks for your work. It's just that we changed the PyPy buildbots to depend on virtualenv, and hit the modern form of issue #794 which this pull request fixes

**Comment by fijal** [comment]
Hi

If maintainers are busy and noone is willing to look properly at this simple review, can you trust us, pypy developers and just merge it? It is a blocker for gettting pypy3 working on windows

**Comment by pradyunsg** [comment]
I'll ping @pfmoore. :)

**Pull request merged**
