### PR TITLE
Silent `unset -f` error in zsh

### PR DESCRIPTION
**Pull request by Gnouc**
With zsh version 5.2, `unset -f function_not_exist` will raise an error:
```
$ unset -f function_not_exist
unset: no such hash table element: function_not_exist
```

`virtualenv` version `14.0.0`, an error message will dump to terminal when source `activate`:
```
$ virtualenv --version
14.0.0

$ virtualenv venv
New python executable in /tmp/venv/bin/python
Installing setuptools, pip, wheel...done.

$ source venv/bin/activate
deactivate:unset:1: no such hash table element: pydoc
```

This pull just silent the error message by redirecting all its output to `/dev/null`.

### CODE REVIEW

**Comment by Gnouc** [comment]
@Ivoz Can you please take a look at it?

**Comment by Ivoz** [comment]
Thanks

**Comment by Namita26** [comment]
had this been solved ? I am still getting the error:
deactivate:unset:1: no such hash table element: pydoc
I have installed the it today only.

**Comment by Gnouc** [comment]
@Namita26 Check your version, AFAICT, the version fixed this error haven't been released yet. See https://github.com/pypa/virtualenv/blob/develop/docs/changes.rst

**Comment by suizman** [comment]
Same here using v14.0.1-1 on Arch

**Comment by Ivoz** [comment]
Now released on 14.0.3

**Comment by sailorsamoor** [comment]
Hello. 
If you use virtualenvwrapper may be suit such script in postmkvirtualenv as a crutch:

`
if [ -n "$VIRTUAL_ENV" ];
then
    sed -i '' '#unset -f pydoc$#s#unset -f pydoc#unset -f pydoc >/dev/null 2>&1#'  $VIRTUAL_ENV/bin/activate
fi
`

**Pull request merged**
