### PR TITLE
Legacy: Use sysconfig.get_default_scheme() where available

### PR DESCRIPTION
**Pull request by hroncok**
sysconfig._get_default_scheme() is gone on Python 3.10

(We support Fedora 32 for another 3 weeks and we still have legacy virtualenv there. I will patch this in, but I wanted to share it. Not tested yet.)

### CODE REVIEW

**Comment by hroncok** [comment]
The bot is changing irrelevant things here :/

**Review by gaborbernat — CHANGES_REQUESTED** [review]
You'll need to fix the CI here.

**Comment by hroncok** [comment]
Do you want me to add a style commit first, or to disable the pre-commit CI on the legacy branch?

**Comment by gaborbernat** [comment]
Definitely don't disable the style check. We need to understand why it's triggered here and not on the master (or other) branches.

**Comment by gaborbernat** [comment]
It's ok to disable pre-commit here.

**Comment by hroncok** [comment]
Thanks.

**Pull request merged**
