### PR TITLE
relocatable activate for bash, dash, zsh, ksh, fish, Windows

### PR DESCRIPTION
**Pull request by jpenney**
Updated activate.bat, activate.fish, and activate.sh that set VIRTUAL_ENV based on where the the activate.* file is sourced or executed from.

See: #11

Also contains tempfile -> mktemp change from #8 since I needed to in order to verify the activate.fish change.

### CODE REVIEW

**Comment by bukzor** [comment]
+1

**Comment by bukzor** [comment]
It's really uncomfortable that this fairly complex behavioral change doesn't necessitate any changes to the test sutie =/

**Comment by Ivoz** [comment]
@bukzor you could call the test suite fairly non-existent atm, which is why :(

**Comment by aknight1969** [comment]
+1

**Comment by BrownTruck** [comment]
Hello!

As part of an effort to ease the contribution process and adopt a more standard workflow pip has switched to doing development on the ``master`` branch. However, this Pull Request was made against the ``develop`` branch so it will need to be resubmitted against ``master``. Unfortunately, this pull request does not cleanly merge against the current ``master`` branch.

If you do nothing, this Pull Request will be automatically closed by @BrownTruck since it cannot be merged.

If this pull request is still valid, please rebase it against ``master`` (or merge ``master`` into it) and resubmit it against the ``master`` branch, closing and referencing the original Pull Request.

If you choose to rebase/merge and resubmit this Pull Request, here is an example message that you can copy and paste:

```
Updated activate.bat, activate.fish, and activate.sh that set VIRTUAL_ENV based on where the the activate.* file is sourced or executed from.

See: #11

Also contains tempfile -> mktemp change from #8 since I needed to in order to verify the activate.fish change.

---

*This was migrated from pypa/virtualenv#236 to reparent it to the ``master`` branch. Please see original pull request for any previous discussion.*
```

**Comment by BrownTruck** [comment]
This Pull Request was closed because it cannot be automatically reparented to the ``master`` branch and it appears to have bit rotted.

Please feel free to re-open it or re-submit it if it is still valid and you have rebased it onto ``master`` or merged ``master`` into it.

**Pull request closed without merging**
