### PR TITLE
activate.sh: drop $_OLD_VIRTUAL_PATH, use remove_from_path instead

### PR DESCRIPTION
**Pull request by blueyed**
Using `$_OLD_VIRTUAL_PATH` will overwrite any changes to $PATH inbetween
activating and deactivating the virtualenv.  It also does not behave
well with `exec $SHELL` (reloading your shell).

`remove_from_path` is taken from pyenv/rbenv's pyenv-which/rbenv-which
shim (https://github.com/sstephenson/rbenv/blob/e851250/libexec/rbenv-which#L18-L27).

### CODE REVIEW

**Comment by Ivoz** [comment]
@blueyed I like the idea of this, however concerned that this might not be portable shell code? We don't have the luxury of demanding bash.

**Comment by BrownTruck** [comment]
Hello!

As part of an effort to ease the contribution process and adopt a more standard workflow pip has switched to doing development on the ``master`` branch. However, this Pull Request was made against the ``develop`` branch so it will need to be resubmitted against ``master``. Unfortunately, this pull request does not cleanly merge against the current ``master`` branch.

If you do nothing, this Pull Request will be automatically closed by @BrownTruck since it cannot be merged.

If this pull request is still valid, please rebase it against ``master`` (or merge ``master`` into it) and resubmit it against the ``master`` branch, closing and referencing the original Pull Request.

If you choose to rebase/merge and resubmit this Pull Request, here is an example message that you can copy and paste:

```
Using $_OLD_VIRTUAL_PATH will overwrite any changes to $PATH inbetween
activating and deactivating the virtualenv.  It also does not behave
well with exec $SHELL (reloading your shell).

remove_from_path is taken from pyenv/rbenv's pyenv-which/rbenv-which
shim (https://github.com/sstephenson/rbenv/blob/e851250/libexec/rbenv-which#L18-L27).

---

*This was migrated from pypa/virtualenv#722 to reparent it to the ``master`` branch. Please see original pull request for any previous discussion.*
```

**Comment by blueyed** [comment]
@BrownTruck / @dstufft
Before rebasing/resubmitting this I'd like to have some feedback about if this is feasible / useful, and would be considered to be merged after all.

@Ivoz 
I could investigate to make this POSIX compatible.

**Comment by BrownTruck** [comment]
This Pull Request was closed because it cannot be automatically reparented to the ``master`` branch and it appears to have bit rotted.

Please feel free to re-open it or re-submit it if it is still valid and you have rebased it onto ``master`` or merged ``master`` into it.

**Pull request closed without merging**
