### PR TITLE
Windows embedable support

### PR DESCRIPTION
**Pull request by reksar**
- [x] ran the linter to address style issues (``tox -e fix_lint``)
- [x] wrote descriptive pull request text
- [x] ensured there are test(s) validating the fix
- [x] added news fragment in ``docs/changelog`` folder
- [ ] updated/extended the documentation

After these steps https://github.com/pypa/virtualenv/issues/1774#issuecomment-619170133
the embeddable Python should works fine with virtualenv.

Virtualenv now ships **zipped** std lib packages along with other **dll** and **pyd** files.

### CODE REVIEW

**Comment by reksar** [comment]
Hm. Looks like last PR must fix 1 test here.

**Comment by gaborbernat** [comment]
Can you rebase the PR on main?

**Comment by reksar** [comment]
I expected the error to occurs in this PR [https://github.com/pypa/virtualenv/pull/2363](https://github.com/pypa/virtualenv/pull/2363) and I fix it. But it seems we need to merge that PR and restart tests here to see logs and catch the error. New logs should tell us more about the error, at least the path to non-existent file.

**Comment by gaborbernat** [comment]
Merged now so you'll need to rebase against main 👍

**Review by gaborbernat — APPROVED** [review]

**Comment by reksar** [comment]
Wow) I expected an exception, but OK)

**Comment by matthuisman** [comment]
with this PR, I'm now getting 
"'PythonInfo' object has no attribute 'version_nodot'"
I have opened an issue below for it
https://github.com/pypa/virtualenv/issues/2367

**Pull request merged**
