### PR TITLE
Declare support for Python 3.6

### PR DESCRIPTION
**Pull request by jonafato**
Per the [changelog](https://github.com/pypa/virtualenv/blob/6d8a4ed81f40223a3f9ea1ba5d11be500d9f667a/docs/changes.rst)
notes for `15.1.0`, Python 3.6 is supported. This change adds 3.6 to the
trove classifiers and drops the now-unsupported 3.3.

### CODE REVIEW

**Comment by gst** [comment]
+1

**Comment by ssbarnea** [comment]
@jonafato Please rebase this change to resolve conflicts. Few minutes ago we merged a change to enable py36 and to remove py33, but that change didn't include any updates in Trove classifiers so your change still makes sense. Don't forget to remove py33 too.

**Comment by jonafato** [comment]
@ssbarnea Rebased.

**Comment by ssbarnea** [comment]
@jonafato @gst : this looks good to me but I would prefer to review and merge https://github.com/pypa/virtualenv/pull/1087 first because it does improve the CI gating considerably and will allow us to better test any other PR, including this one.

It may not be obviously but anyone can review.

**Comment by hugovk** [comment]
This is a trivial change, it doesn't really need to wait for #1087. I'd just merge it to reduce the backlog.

**Pull request merged**
