### PR TITLE
CentOs and Fedora support

### PR DESCRIPTION
**Pull request by gaborbernat**
Instead of hard coding patterns and guessing let's ask the host python via the sysconfig (for stdlib) and distutils install (for virtualenv elements - we target pip installable envs here).

Resolves https://github.com/pypa/virtualenv/issues/1332

TODO:
[ ] validate again with Fedora
[ ] validate again with CentOS
[ ] add test for --copies

### CODE REVIEW

**Comment by ssbarnea** [comment]
I am extreamly happy to see this ticket raised. I can provide help on achieving this as I had to do the same distro-testing with other python packages, for the same scope: to test that we don't break on these.

**Comment by gaborbernat** [comment]
@ssbarnea thank you very much. I'll merge this PR, I've tested on Fedora 29 and CentOS 7 and for myself, the test suite passed with flying colours. Feel free to take the code out for a sping yourself and let me know if you run into any issues. 

There exists one slight discrepancy between what the builtin venv module does and what we do. The platform library folder (``lib64``) symlinks to the pure library folder (``lib``). I prefer to not do but instead create two folder hierarchies. For all my tests this did not seem to matter, and both of those are added to the ``sys.path``. Until someone can point me why the symlink should be preferable I'll leave with this approach. On CentOS I've only found ``python2.7`` and ``python3.6``, so I've tested only those two (also ran ``python3.8`` but I've built this from source, so I consider it not an exact match, as the upstream binary patches are missing). Any way to get the other pythons?

CC @hroncok you might be interested in this.

**Comment by hroncok** [comment]
> I've tested on Fedora 29

I can test this somehow on Fedora 31 if needed. 29 is out of support. But our patches are the same regarding lib64.

Not creating the symbolic link is probably OK. cc @encukou @stratakis

**Comment by hroncok** [comment]
> Any way to get the other pythons?

On CentOS 7, I only know about 2.7, 3.4 (in EPEL) and 3.6.

On recent Fedoras, there should be anything from 2.6, 2.7, 3.4-3.9 and pypy2+3.

**Comment by gaborbernat** [comment]
Yeah on fedora I could get all those easily and the test suite passed 😎

**Pull request merged**
